/**
 * Generates the Rust mirror of the canonical {@link ErrorCode} list so both
 * languages speak the same `E_*` wire strings. **TS is the source of truth**
 * (`./src/index.ts`); the Rust file is generated + committed, and a drift test
 * (`error-codes.gen.test.ts`) fails CI if the two ever diverge.
 *
 * Two inputs, split by how much we trust them:
 *  - **Values** come from importing the runtime object — the contract, never a
 *    fragile parse.
 *  - **Doc comments** are scraped from the source with a regex — purely
 *    cosmetic; a miss drops a `///` line but never corrupts a code.
 *
 * Run `bun run gen:rust` (or `bun gen-rust.ts`) to (re)write the Rust file.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { ErrorCode } from './src/index.ts';

const here = dirname(fileURLToPath(import.meta.url));
const TS_SOURCE = join(here, 'src/index.ts');
export const RUST_TARGET = join(here, '../../crates/lenke-engine/src/error_codes.rs');

/** name → one-line JSDoc, scraped from the const-object members. Best-effort. */
const docComments = (): Map<string, string> => {
  const text = readFileSync(TS_SOURCE, 'utf8');
  const docs = new Map<string, string>();
  // Matches `  /** A doc. */` immediately above `  Name: 'E_VALUE',`.
  const member = /\/\*\* (.+?) \*\/\s*\n\s*([A-Za-z][A-Za-z0-9]*):/g;

  for (const [, doc, name] of text.matchAll(member)) {
    docs.set(name, doc);
  }

  return docs;
};

/** Render the full `error_codes.rs` module as a string (used by the drift test too). */
export const renderRustModule = (): string => {
  const docs = docComments();
  const entries = Object.entries(ErrorCode) as Array<[string, string]>;

  const variants = entries
    .map(([name]) => {
      const doc = docs.get(name);

      return `${doc ? `    /// ${doc}\n` : ''}    ${name},`;
    })
    .join('\n');

  const arms = entries
    .map(([name, value]) => `            ErrorCode::${name} => "${value}",`)
    .join('\n');
  // Rendered one-per-line to match `rustfmt` output, so the generated file is
  // format-stable (a stray `cargo fmt` won't rewrite it and trip the drift test).
  const all = entries.map(([name]) => `        ErrorCode::${name},`).join('\n');

  return `// @generated by packages/errors/gen-rust.ts — DO NOT EDIT BY HAND.
//
// Mirror of the canonical error codes. Source of truth: the @lenke/errors
// const object in packages/errors/src/index.ts. Regenerate with
// \`bun run gen:rust\` in packages/errors; the error-codes.gen drift test fails
// if this file is stale.
//
// The **string is the contract** (it crosses the FFI boundary verbatim), so the
// JS side matches \`error.code === ErrorCode::*.as_str()\` with no shared binary
// ABI. Never reuse or repurpose a value once shipped.

/// Canonical, stable error codes shared with the TypeScript packages.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[allow(dead_code)] // not every code is thrown from Rust yet; the contract is shared regardless.
pub enum ErrorCode {
${variants}
}

#[allow(clippy::use_self)] // generated; the paths below spell out the explicit type name.
impl ErrorCode {
    /// Every code, for exhaustiveness checks and the cross-language conformance test.
    pub const ALL: &'static [ErrorCode] = &[
${all}
    ];

    /// The stable \`E_*\` wire string. This is what crosses the FFI boundary.
    pub const fn as_str(&self) -> &'static str {
        match self {
${arms}
        }
    }
}
`;
};

if (import.meta.main) {
  writeFileSync(RUST_TARGET, renderRustModule());
  // eslint-disable-next-line no-console
  console.log(`wrote ${RUST_TARGET}`);
}
